title: Firestarter
description: Blog about Windows and Mac

url: 
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: Downloads
   url: /downloads

social:
   github: victor-talpeanu
   twitter: firestarterfdsk
   facebook: 
   email: victor.talpeanu@gmail.com

google_analytics: "UA-67982267-1"
excerpt_separator: <!--more-->