# Site settings
title: Firestarter - A blog about little this % little that
email: victor.talpeanu@gmail.com
description: A blog about little this % little that.
url: "" # the base hostname & protocol for your site
twitter_username: firestarterfdsk
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Victor Talpeanu
      layout: "post"
      category: windows
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"





