# Site settings
title: Firestarter - A blog about web conferences
email: victor.talpeanu@gmail.com
description: A blog about Windows an Mac.
url: "http://webconfs.me" # the base hostname & protocol for your site
twitter_username: 
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Victor Talpeanu
      layout: "post"
      category: conferences
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"





