title: Firestarter
description: Blog about Windows and Mac

url: 
baseurl: ""
paginate_path: "blog/page:num/"
permalink: /:title

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: 
   twitter: 
   facebook: https://www.facebook.com
   email: victor.talpeanu@gmail.com

google_analytics: "UA-67982267-1"
